POST http://localhost:4000/movies/
Content-Type: application/json

{
    "director_id":26,
 "movie_name":"sai",
 "lead_actor":"harsha"
}
###
put http://localhost:4000/movies/58/
Content-Type: application/json

{
    "director_id":26,
 "movie_name":"sai",
 "lead_actor":"Harsha"
}