POST http://localhost:4000/movies/
Content-Type: application/json

{
    "directorId":26,
 "movieName":"sai",
 "leadActor":"harsha"
}
###
put http://localhost:4000/movies/58/
Content-Type: application/json

{
    "directorId":26,
 "movieName":"sai",
 "leadActor":"Harsha"
}
###
DELETE http://localhost:4000/movies/58/
###
GET http://localhost:4000/directors/
